pluginManagement {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        mavenCentral()
    }
}
rootProject.name = "MirotalkTV"
include ':app'
