plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sinovo.mirotalktv'
    compileSdk 34

    defaultConfig {
        applicationId "com.sinovo.mirotalktv"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    // 提供 WebView 兼容与潜在的安全/媒体能力增强
    implementation 'androidx.webkit:webkit:1.10.0'
}
